### ISSUE TITLE
Stable release?

### ISSUE THREAD

**Issue by OndrejSpanel** [UdashFramework/udash-core#1029]
It seems last stable release is still 0.8.0, there are only milestone releases for 0.9.x. What are the plans for the future?

The 0.8.0 does not even support Scala.js 1.x, therefore it looks kind of obsolete now.

**Comment by ddworak** [comment]
Hi! Thanks for asking. Yeah, we're mostly using 0.9.x milestones and even the demos are mostly updated for that. I'll try to wrap up 0.9.0 with the current featureset and do a proper release ;)

**Comment by OndrejSpanel** [comment]
Thanks, that sounds real good.

**Comment by ddworak** [comment]
https://github.com/UdashFramework/udash-core/releases/tag/v0.9.0
