### ISSUE TITLE
Using `JSDependenciesPlugin` in a cross-project breaks CSS processing

### ISSUE THREAD

**Issue by OndrejSpanel** [UdashFramework/udash-core#1094]
See https://github.com/scala-js/jsdependencies/issues/51

> as soon as one enables `JSDependenciesPlugin`, CSS macros stop working and output of `CssRender.render` is empty.

**Comment by OndrejSpanel** [comment]
It seems the resolution is to use `.jsConfigure(_.enablePlugins(JSDependenciesPlugin))`, not just `.enablePlugins(JSDependenciesPlugin)`.

**Comment by ddworak** [comment]
@OndrejSpanel I'd say that's expected, this plugin is not intended for JVM projects.

**Comment by OndrejSpanel** [comment]
Understood. I was not using it for a JVM project intentionaly, I just was not aware of `jsConfiguration` and just applied `.enablePlugins` on the cross-project. Now I am aware more what it does I am surprised the project almost worked (and it is not clear to me why it worked with Scala 2.12 and Udash 0.8.0, but I guess nobody is interested in understanding that).

I am glad I have found the cause, all my projects using Udash seem now fully ported to 0.9.0.
