### ISSUE TITLE
How to integrate Bootstrap template

### ISSUE THREAD

**Issue by zoosky** [UdashFramework/udash-core#112]
What would be the best way to integrate a Bootstrap template such as https://github.com/almasaeed2010/AdminLTE into Udash?

**Comment by Starzu** [comment]
Hi @zoosky! I never tried to do it. Anyway:
* you should include template's JS/CSS files
* you can wrap new CSS classes like [here](https://github.com/UdashFramework/udash-core/blob/master/bootstrap/frontend/src/main/scala/io/udash/bootstrap/statics.scala)
* you can wrap new JS components like [here](https://github.com/UdashFramework/udash-core/blob/master/bootstrap/frontend/src/main/scala/io/udash/bootstrap/button/UdashButton.scala)

If you have any more specific questions I will be happy to help.
