### ISSUE TITLE
DefaultServerREST is missing an option to use HTTPS

### ISSUE THREAD

**Issue by esamson** [UdashFramework/udash-core#132]
I'm trying to create a REST client, following the examples in http://guide.udash.io/#/rest/client-server but my backend server is HTTPS only. It seems there is no way to specify HTTPS when using DefaultServerREST.

I'm using udash 0.5.0.

**Comment by Starzu** [comment]
@esamson It's definitely a bug. `DefaultRESTConnector` should accept protocol version in constructor. Could you create PR with this improvement?
