### ISSUE TITLE
RadioButtons should support generic Properties

### ISSUE THREAD

**Issue by dthoma** [UdashFramework/udash-core#161]
Bi-Directional data binding for RadioButtons (and similar inputs) currently only work for String-Properties. This is an unnecessary restriction that causes a lot of boiler plate. Here is an suggestion for the implementation of a typesafe RadioButtons:

```scala
object TypedRadioButtons {
  def apply[A, B](property: Property[A], options: Seq[(A, B)],
      decorator: Seq[(html.Input, A, B)] => JsDom.TypedTag[html.Element], xs: Modifier*): 
  JsDom.TypedTag[html.Element] = {
    val uuid = java.util.UUID.randomUUID().toString
    decorator(options.map(opt => {
      val in = input(tpe := "radio", name := uuid, onchange :+= ((event: Event) => {
        property.set(opt._1)
      }))(xs: _*).render
      in.checked = property.get == opt._1
      property.listen { _ =>
        in.checked = property.get == opt._1
      }
      (in, opt._1, opt._2)
    }))
  }

}
```

It takes any property of type A, a Seq, that contains Tuples associating the property values with some additional information of type B. That information can be used to generate the labels, so it can be text or some html elements.

**Comment by Starzu** [comment]
Hi @dthoma, I'll include bidirectional bindings refactoring in the next release.
