### ISSUE TITLE
Scala.js 1.0

### ISSUE THREAD

**Issue by Starzu** [UdashFramework/udash-core#204]

**Comment by ddworak** [comment]
2.13 done within https://github.com/UdashFramework/udash-core/issues/335

**Comment by ddworak** [comment]
https://www.scala-js.org/news/2019/11/26/announcing-scalajs-1.0.0-RC1/

**Comment by OndrejSpanel** [comment]
https://www.scala-js.org/news/2020/02/25/announcing-scalajs-1.0.0/

Is there something I could do to help porting to 1.0?

**Comment by ddworak** [comment]
@OndrejSpanel I'll take a look at it and let you know if there are any blockers, there just wasn't much interest so far (and not all libraries we work with were available for 1.0).

**Comment by ddworak** [comment]
We're now waiting for our commons library (https://github.com/AVSystem/scala-commons) to upgrade. It is tested against e.g. circe (https://github.com/circe/circe/issues/1407) and Monix (https://github.com/monix/monix/issues/1131), so please be patient for a while more and stay tuned :)

**Comment by OndrejSpanel** [comment]
There is no hurry. Thanks for your effort.

**Comment by ddworak** [comment]
udash-rest depends on https://github.com/softwaremill/sttp/issues/454

**Comment by ddworak** [comment]
https://github.com/japgolly/scalacss/issues/205

**Comment by ddworak** [comment]
0.9.0-M2 is now available for SJS 1.x and Scala 2.12/2.13

https://repo1.maven.org/maven2/io/udash/udash-core_sjs1_2.12/
https://repo1.maven.org/maven2/io/udash/udash-core_sjs1_2.13/
