### ISSUE TITLE
File upload support

### ISSUE THREAD

**Issue by Starzu** [UdashFramework/udash-core#21]
### TODO

* prepare utils for file uploading forms
* create a demo application in the Udash demos repo
* describe the created utils in Dev's Guide

**Comment by Starzu** [comment]
Done in #67

**Comment by ddworak** [comment]
Demo and guide don't seem to have been done, maybe we should create separate issues for these then in corresponding projects?

**Comment by Starzu** [comment]
Demo is already merged, guide is waiting for review.
