### ISSUE TITLE
Material Design support

### ISSUE THREAD

**Issue by Starzu** [UdashFramework/udash-core#24]
### Description

Prepare support for the Material Design components. (Similar to #20)

This might be useful: https://getmdl.io/
### TODO
- prepare a wrapper for Material design components
- prepare the wrapper interface to be used with Udash Properties
- create a demo application in the Udash demos repo
- create the Material Design chapter in Dev's Guide

**Comment by Starzu** [comment]
@v6ak We don't have resources to create and maintain another components library wrapper. For now the target is to upgrade bootstrap components to Bootstrap 4. Probably some day we will reopen this issue. ;)

**Comment by v6ak** [comment]
Thank you for the info.
