### ISSUE TITLE
CORS handling with Udash REST

### ISSUE THREAD

**Issue by Passarinho4** [UdashFramework/udash-core#275]
Hi, 
is it possible to add headers required to allow CORS with Udash REST? 
Actually, the OPTIONS requests are handled automatically and in the response, there is only Allow header -> The Access-Control-Allow-Origin is not available. Is it possible to add it (or maybe my custom Headers too) somehow? Or maybe should I handle it in a different way?

I strongly believe that this use case is very common, so this framework should have a way to handle this. Have you any suggestions?

**Comment by ghik** [comment]
I'm not yet sure how to handle this in general, but it should be relatively easy to hack by appropriately adjusting the `HandleRequest` function on the server side, for example:

```scala
def corsAware(handle: HandleRequest): HandleRequest = request => {
  if (request.method == HttpMethod.OPTIONS)
    RawRest.mapAsync(handle(request)) { response =>
      response.copy(headers = response.headers.append("Access-Control-Allow-Origin", PlainValue("*")))
    }
  else
    handle(request)
}
```

**Comment by Passarinho4** [comment]
Ok, this hack works pretty well. Thanks! :)
