### ISSUE TITLE
reduce size of generated application size

### ISSUE THREAD

**Issue by avkonst** [UdashFramework/udash-core#34]
Hi,

Thanks for the nice framework. I learnt new things reading it's code and playing with it. Is there a way to reduce size of a file of the final application?

I have got the following file sizes after fullOptJS (for udash-generator generated frontend):
deps.js 84KB
init.js 1KB
impl.js 707KB

The last one is really fat file...  questioning the idea of using scalajs + udash...
I suspect impl.js is composed of:
- udash framework
- scalatags
- scalacss
- udash wrapped jquery
- something else?

How could it be improved?

**Comment by avkonst** [comment]
I checked the output JS size with https://github.com/ThoughtWorksInc/Binding.scala-sample. It is 250KB in total together with all dependencies.. I know it is not fair comparison, because udash is more feature-rich, but still it is several times bigger.

**Comment by Starzu** [comment]
I'm affraid that this is a ScalaCSS problem. (https://github.com/japgolly/scalacss/issues/83)

In my playground project (from Udash generator but modified a little) after removing ScalaCSS, JS file size drops down from 828KB to 352KB.

**Comment by avkonst** [comment]
cool. thanks!
