### ISSUE TITLE
ServerConnector onReconnect  handler is not compatible with atmosphere lifecycle

### ISSUE THREAD

**Issue by mereszeta** [UdashFramework/udash-core#394]
# Problem description:
 According to https://github.com/Atmosphere/atmosphere/wiki/Understanding-JavaScript-functions onReconnect is being called every time there is a need to reconnect, but it doesn't mean successful reconnect attemp, while in ``io.udash.rpc.internals.ServerConnector`` onReconnect uses timeout which changes connectionStatus to open. While it's needed internally in the same class (it provides actual reconnection attempt) it also produces side effects such as status open while connection can still be unavailable. 
# Proposed solution:
``io.udash.rpc.ConnectionStatus`` should be enhanced with value such as 'Reconnecting' which would still allow reconnecting but wouldn't be misleading for framework users.

**Comment by ddworak** [comment]
Closing in favour of https://github.com/UdashFramework/udash-core/issues/26
