### ISSUE TITLE
UdashButton with UdashDropdown

### ISSUE THREAD

**Issue by Starzu** [UdashFramework/udash-core#400]
Releated to #379 

`UdashButton` after refactoring does not work well with `UdashDropdown` - it's broken even in the guide example. 

In order to make dropdown buttons look as expected I have to use something like that:
```scala
buttonFactory = content => UdashButton(tag = ButtonTag.Anchor)(nested => Seq[Modifier](content(nested), href := "", tpe := "", cls := "nav-link dropdown-toggle"))
```

**Comment by mereszeta** [comment]
@Starzu could you elaborate about example snipped and expected behavior?

**Comment by Starzu** [comment]
@mereszeta Take a look at the second NavBar demo in Udash Guide. 
![image](https://user-images.githubusercontent.com/817407/70389361-d4080f00-19be-11ea-9979-253adb10a218.png)

Styling of dropdown buttons is broken. Compare it with Bootstrap 4 demo:
![image](https://user-images.githubusercontent.com/817407/70389381-07e33480-19bf-11ea-9272-df973b4e1048.png)

The snippet above fixes the button style, but it should be more user friendly.
