### ISSUE TITLE
Migrate and upgrade udash-demos

### ISSUE THREAD

**Issue by ddworak** [UdashFramework/udash-core#518]

**Comment by Ktedon** [comment]
Is this for scala 3?

**Comment by ddworak** [comment]
This is actually invalid - https://github.com/UdashFramework/udash-demos are archived and replaced by the g8 template https://github.com/UdashFramework/udash.g8. Scala 3 is a separate matter which has to be resolved in this repository first - not soon though, as many of the libraries we heavily use are not there yet.
