### ISSUE TITLE
Missing documentation for clearsProperty

### ISSUE THREAD

**Issue by OndrejSpanel** [UdashFramework/udash-core#555]
ScalaDoc is missing documentation for `clearsProperty` parameter:

https://github.com/UdashFramework/udash-core/blob/4cc35fae02d810af5b81c18f3ca0aed67076987b/core/src/main/scala/io/udash/properties/seq/Patch.scala#L6-L14

My guess is it means the sequence is now empty as a result of the change, but I am not sure.

**Comment by ddworak** [comment]
@OndrejSpanel thank you for the report. That's my understanding as well, we'll check if all implementations in the library respect that (and if that optimization is still needed).
