### ISSUE TITLE
A lot of replacement characters at guide's License

### ISSUE THREAD

**Issue by catap** [UdashFramework/udash-core#640]
Good day!

I just discovered that license at https://guide.udash.io/license has a lot of replacement characters. You can see it at attache screenshot.
![Screenshot 2020-08-30 at 23 48 36](https://user-images.githubusercontent.com/37775/91670221-ad28d480-eb1b-11ea-8f99-5ddda40757f7.png)

**Comment by ddworak** [comment]
We had some locale issue on the VM, should be fine again. Thanks for reporting!
