### ISSUE TITLE
Scala-2.13 complains to nested style

### ISSUE THREAD

**Issue by catap** [UdashFramework/udash-core#647]
When I try to use nested CSS styles at scala-2.13 I had complains like this:
```
Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method &,
or remove the empty argument list from its definition (Java-defined methods are exempt).
In Scala 3, an unapplied method like this will be eta-expanded into a function.
    &.focus(
    ^
```
to fix it I need to replace this line to `&().focus` that a bit strange.

**Comment by ddworak** [comment]
This was fixed in M4 - please verify and confirm :)

**Comment by catap** [comment]
@ddworak yes, `M4` fixed it and I'd love to confirm that.

Anyway, I also would like to share that `&().focus` doesn't work at `M4` with error:
```
value focus is not a member of scalacss.internal.StyleS
```

Anyway, I don't think that this should be fixed.
