### ISSUE TITLE
interoperate with Binding.scala/dom?

### ISSUE THREAD

**Issue by PhilAndrew** [UdashFramework/udash-core#77]
can udash interoperate with this? it seems like it is like react but better.  interoperability would help udash and give the binding library features it doesn't have like rpc

https://github.com/ThoughtWorksInc/Binding.scala

**Comment by Starzu** [comment]
As you can see in [Developer's Guide](http://guide.udash.io/#/frontend/bindings) Udash contains binding system. Anyway I can't see what kind of integration you mean. I think Udash RPC can be combined with Binding.scala without problems.

Could you provide more details of your integration idea?

**Comment by l3ug1m** [comment]
Change the "View" part of the "Model, View, Presenter & ViewPresenter" used by udash.io to scala.binding
Taking advantage of the structure of router and presenter

I have this idea
