### ISSUE TITLE
Proposal: support for endpoints library

### ISSUE THREAD

**Issue by Krever** [UdashFramework/udash-core#81]
Hi there,

I see that Udash has adressed problem of typesafe REST. calls I would like to just mention there is this this great library that allows to define typesafe REST in a way that allow easy implementation on both sides, client and server. Here is a link https://github.com/julienrf/endpoints/ . You may consider switching to /supporting, as I think it is superset of functionality that Udash provides. 

I'm not directly connected to this library, but I think it is great concept and deserves some attentions.
It's just a proposal, you will know best if it will be good for Udash :)

**Comment by Starzu** [comment]
Hi @Krever,

thank you for proposal and sorry for such a late answer. I have missed this issue somehow... I think we should expand REST support in future, so I will keep this issue open and consider proposed library when the time comes.

**Comment by Starzu** [comment]
As part of #107 we have considered this, but we are going to keep our tooling, based on RPC interfaces, as an alternative solution. 

I'm closing this issue, but thanks again for proposal.
