### ISSUE TITLE
Missing "rest" in generated FE

### ISSUE THREAD

**Issue by mnn** [UdashFramework/udash-core#90]
Hello! I am trying out your framework and I have to say it looks really great.

To the point - I have let the generator do its work, selected FE-only project, and tried few trivial things. I wanted to try some REST, but I don't seem to be able to import stuff from `rest` object via

```
import io.udash.rest._
```

unfortunately I am getting:

```
object rest is not a member of package io.udash
```

Any idea what I could be doing wrong?

PS: Adding some stuff I dig from a build file:
```
scalaVersion in ThisBuild := "2.11.8"

  val udashVersion = "0.4.0"
  val udashJQueryVersion = "1.0.0"
  val logbackVersion = "1.1.3"

    "io.udash" %%% "udash-core-frontend" % udashVersion,
    "io.udash" %%% "udash-jquery" % udashJQueryVersion,
    "com.github.japgolly.scalacss" %%% "core" % "0.5.0",
    "com.github.japgolly.scalacss" %%% "ext-scalatags" % "0.5.0"
```

**Comment by Starzu** [comment]
Hi @mnn, you should add `"io.udash" %%% "udash-rest-shared" % "0.4.0"` in your dependencies.

**Comment by mnn** [comment]
Thank you very much @Starzu, it's working now :smile:.
