### ISSUE TITLE
Custom object without case-class wrapper for RPC endpoint

### ISSUE THREAD

**Issue by catap** [UdashFramework/udash-core#919]
Let assume that I'd like to make a simple RPC endpoint which returns custom object. This object is came from some 3rd party library which is cross compiled to Scala.JS and Scala. As good example let me use: `java.time.Instant`.

So, the code: 
```scala
object AdditionalGenCodecs {
  implicit val instantGenCodec: GenCodec[Instant] =
    GenCodec.nullableSimple(i => {
      val seconds = i.readLong()
      val nanos = i.readLong()
      Instant.ofEpochSecond(seconds, nanos)
    }, (out, v) => {
      out.writeLong(v.getEpochSecond)
      out.writeLong(v.getNano)
    })
}

trait ServerPartyRPC {
  def getMoment: Future[Instant]
}

object ServerPartyRPC extends DefaultServerRpcCompanion[ServerPartyRPC]
```

This code can't be compiled with error:
```
Macro at line 23 failed: cannot translate between trait ServerPartyRPC and trait ServerRawRpc:
problem with method getMoment:
 * Raw method call did not match:
   No GenCodec found for java.time.Instant
 * Raw method get did not match:
   scala.concurrent.Future[java.time.Instant] is not a valid server RPC trait, does it have a companion object that extends DefaultServerRpcCompanion or other similar companion base class?
 * Raw method fire did not match:
   real result type scala.concurrent.Future[java.time.Instant] does not match raw result type Unit
  def getMoment: Future[Instant]
```

Anyway, as soon as I wrap it into simple `case class`, I can use `HasGenCodecWithDeps`: 
```scala
@transient
case class MyInstant(instant: Instant)
object MyInstant extends HasGenCodecWithDeps[AdditionalGenCodecs.type, MyInstant]
```

Which allows to convert my RPC to:
```scala
trait ServerPartyRPC {
  def getMoment: Future[MyInstant]
}
object ServerPartyRPC extends DefaultServerRpcCompanion[ServerPartyRPC]
```

Which is working fine.

I feel that udash has missed `DefaultServerRpcCompanionWithDeps` and `DefaultClientRpcCompanionWithDeps`.

Or I haven't figured out how to use it?

**Comment by ddworak** [comment]
In your example, I think you meant `@transparent`, not `@transient`, right?

`Instant.ofEpochSecond(seconds, nanos)` is actually not implemented in SJS standard library, but I'll assume you have an external library filling that. In that case such companion could be useful :)

https://github.com/UdashFramework/udash-core/pull/921

**Comment by catap** [comment]
@ddworak yeah, you're defently right. I mean `@transparent` :)

Thus, `Instant.ofEpochSecond(seconds, nanos)` available via nice hack: https://github.com/scala-js/scala-js/blob/main/javalib-ext-dummies/src/main/scala/java/time/Instant.scala

And thanks for fix it allows to remove tons of wrappers.

**Comment by ddworak** [comment]
Closed by https://github.com/UdashFramework/udash-core/pull/921
