### ISSUE TITLE
Support urls without hash

### ISSUE THREAD

**Issue by omj** [UdashFramework/udash-core#98]
Hi, many popular client side frameworks now support urls without hash (#). It would be nice to have this feature in udash. Thank you!

**Comment by Starzu** [comment]
@omj Thanks for the proposition. I'll take a look at it.

**Comment by ostrain** [comment]
This would be a great enhancement, hash URLs are pretty dated at this point. The pushState API has been around for many years and is very widely supported by clients: https://caniuse.com/#feat=history

**Comment by Starzu** [comment]
We want to finish performance-oriented changes and release version `0.6`. Feel free to contribute if you want this change in the next release.

**Comment by leonardehrenfried** [comment]
Is it going to be as easy as changing https://github.com/UdashFramework/udash-core/blob/faa6572a112290813d72b3ee51346f9ec293eb36/core/frontend/src/main/scala/io/udash/routing/UrlChangeProvider.scala#L23 to use `pushState` (https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_pushState()_method)?

**Comment by Starzu** [comment]
Migration of Udash Guide: https://github.com/UdashFramework/udash-guide/commit/cc54f57cc2128e446e1df1c29f65d0baa97c6fc9
